### ISSUE TITLE
Differentiate delegation of inheritance vs parenthood

### ISSUE THREAD

**Issue by expede** [ucan-wg/UIPs#3]
@matheus23 raised an important ambiguity in wildcard delegation (`att: *`) between re-delegating all proofs in scope (better space use), and delegating a parenthood relation (better expressivity). IN pictures (apologies for the mangled Granovetter diagrams)

Typical linking flow, where we want to also delegate any resources that _will be created in the future_:

<img width="527" alt="Screen_Shot_2022-01-11_at_20-1 24 31" src="https://user-images.githubusercontent.com/1052016/149234892-f81da382-1712-4574-bdf6-1a45521591b7.png">

It's easy to fall into thinking of this as being for one human with multiple keys. However the system is human-agnostic. To illustrate the difference between the two senses of the wildcard, here is a convoluted scenario that should be supportable:

<img width="584" alt="Screen_Shot_2022-01-11_at_20 24 36" src="https://user-images.githubusercontent.com/1052016/149235141-171a7e4c-981c-49c9-9527-4aaab0cd370e.png">

Note that in the diagram above, Philipp doesn't delegate access to his "stuff".

There are a couple solutions (we would find better names for these fields, but as a sketch):

* Separate tags
  * `att: ["ALL_PARENTHOOD", "REDELEGATE_ALL"]`
* Passthrough redelegation and/or parenthood delegation separate from `att`
  * e.g. `att: [], pass: ["Qmabcdef", "bafyxyz"], par: true`
* Separate senses as capabilities
  * `att: [{with: "boris.fission.name/*", can: "*"}, {with: "PROOFS", can "*"}]`

**Comment by expede** [comment]
@matheus23 anything additional thoughts?

**Comment by matheus23** [comment]
The diagrams & problem at hand are clear to me.
I'm not sure what the best solution to the problem is yet.

> Separate senses as capabilities 
> `att: [{with: "boris.fission.name/*", can: "*"}, {with: "PROOFS", can "*"}]`

I assume the first one means "give all rights to boris.fission.name" and the second one is "delegate all from proofs".

I think the first one doesn't quite achieve what we described initially: Delegating all rights that a DID has and will have in the future. It "just" gives you "all rights to the boris fission account", if I understand that correctly. Which *does* solve our use case for now, but I think it's still useful to capture what we've been describing initially. I.e. does it also delegate all rights to `boris.web3.storage`, assuming something like that would exist & he'd have the same original DID registered with web3storage?

---

Between the last two options, I feel like the `att: ["ALL_PARENTHOOD", "REDELEGATE_ALL"]` option is just the simpler one, so I'd vouch for that. The other option pulls in CIDs & hashing and adds more fields.

I was trying to maybe come up with an alternative term for `ALL_PARENTHOOD` and was looking for some term that describes giving parenthood to someone else. I'd like it to be a verb like `REDELEGATE_ALL`, but I can only come up with two (admittedly obscure) nouns: surrogate and godparent. And surrogate is overloaded anyway.
Or maybe as simple as `DELEGATE_RIGHTS`, `DELEGATE_ALL`? (In contrast to **`RE`**`DELEGATE_ALL`)

**Comment by expede** [comment]
Quick note that @matheus23 and I walked through briefly in a call earlier today:

I'm writing the UCAN v0.8 spec right now, and experimenting with separating the pointer and action semantics. It's feels a bit weird in places (much larger number of possible states), but we could encode the above in a consistent format, something like:

```json
[
  { "with": "ucan://.", "can": "ucan/*"},
  { "with": "did:key:zALICE", "can": "ambient/*"},
]
```

**Comment by expede** [comment]
Closed by https://github.com/ucan-wg/spec/pull/10
